version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    container_name: goodapi
    build: .
    env_file: ".env"
    ports:
      - "3000:3000"
volumes:
  postgres_data: